import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Header } from '@/components/Header';

import { MindMapProvider } from '@/context/MindMapContext';
import { AuthProvider } from '@/components/providers/auth-provider';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-50`}>
        <AuthProvider>
          <MindMapProvider>
            <Header />
            <main className="min-h-screen pt-16">
              {children}
            </main>
          </MindMapProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
